export {
  RTE_BRAND_PATH,
  RTE_DEV_TOKEN_PATH,
  RTE_PCC_PATH,
  RTE_WS_PATH,
} from "./constants.js";
export {
  RTE_DEV_TOKEN_QUERY,
  bearerTokenFromHeader,
  devTokenFromUpgradeUrl,
  isAllowedRteOrigin,
  isValidDevToken,
} from "./dev-auth.js";
export {
  BRAND_APPLY_ACTIONS,
  BRAND_BUTTON_VARIANTS,
  BRAND_BUTTON_HOVERS,
  BRAND_CARD_HOVERS,
  BRAND_CARD_SHADOWS,
  BRAND_ACCENT_COLORS,
  BRAND_COLORS,
  BRAND_DENSITY,
  BRAND_RADIUS,
  BRAND_SURFACES,
  BRAND_TYPOGRAPHY,
  BRAND_BUTTON_HOVER_FIELD_LABEL,
  BRAND_BUTTON_VARIANT_FIELD_LABEL,
  BRAND_CARD_HOVER_FIELD_LABEL,
  BRAND_CARD_SHADOW_FIELD_LABEL,
  BRAND_SURFACE_FIELD_LABEL,
  brandConfigSchema,
  brandConfigsEqual,
  brandFragmentHostHint,
  brandColorsForAction,
  brandPresetDimensionsForAction,
  buildBrandClassFragment,
  buildBrandPatchOps,
  buildBrandPreviewSummary,
  BRAND_PRESET_DIMENSIONS_BY_ACTION,
  BRAND_ACCENT_SLOT_BY_ACTION,
  BRAND_RADIUS_FIELD_LABEL,
  BRAND_DENSITY_FIELD_LABEL,
  DEFAULT_BRAND_CONFIG,
  getBrandColorLabel,
  getBrandColorSlotLabel,
  getBrandDensityLabel,
  getBrandRadiusLabel,
  getBrandButtonVariantLabel,
  getBrandButtonHoverLabel,
  getBrandCardHoverLabel,
  getBrandCardShadowLabel,
  getBrandSurfaceLabel,
  getBrandTypographyFieldLabel,
  getBrandTypographyLabel,
  isBrandAccentColor,
  normalizeBrandConfig,
  serializeBrandConfig,
  type BrandAccentSlot,
  type BrandApplyAction,
  type BrandButtonHover,
  type BrandButtonVariant,
  type BrandCardHover,
  type BrandCardShadow,
  type BrandAccentColor,
  type BrandColor,
  type BrandConfig,
  type BrandConfigFileV2,
  type BrandDensity,
  type BrandFragmentHostHint,
  type BrandPresetDimension,
  type BrandRadius,
  type BrandSurface,
  type BrandTokens,
  type BrandTypography,
} from "./brand-kit.js";
export {
  BRAND_PAGE_DISCOVERY_PLURALS,
  buildBrandPageDiscoveryLine,
  type BrandPageDiscoveryCounts,
} from "./brand-page-discovery.js";
export {
  buildBrandBulkPatchOps,
  buildBrandValidateSummary,
  /** @deprecated Use {@link buildBrandValidateSummary}. */
  buildBrandBulkPreviewSummary,
  buildBrandBulkTargetOps,
  entryMatchesBrandBulkAction,
  filterBrandBulkCandidates,
  resolveBrandBulkPatchHostId,
  type BrandBulkFilterOptions,
  type BrandBulkTarget,
} from "./brand-bulk.js";
export {
  inferBrandPresetsFromClassName,
  inferBrandPresetsFromTokens,
  inspectBrandMatch,
  inspectBrandMatchForAction,
  type BrandInspectDimension,
  type BrandInspectResult,
  type BrandInspectRow,
  type BrandInspectStatus,
} from "./brand-inspector.js";
export {
  isBrandableEntry,
  isNonBrandableNavEntry,
  resolveBrandCategoryForEntry,
} from "./brand-selection.js";
export {
  defaultPccManifestPath,
  isPccBrandableCategory,
  isPccRejectedCategory,
  isPccSupportedCategory,
  parsePccManifest,
  PCC_BRANDABLE_CATEGORIES,
  PCC_REJECTED_CATEGORIES,
  PCC_SUPPORTED_CATEGORIES,
  pccCategoryLabel,
  pccHostsForCategory,
  type PccCategory,
  type PccCategoryConfig,
  type PccManifest,
  type PccManifestParseError,
  type PccRejectedCategory,
} from "./coverage-contract.js";
export {
  evaluateBrandPageScan,
  pccBrandableHostIds,
  type BrandCategoryScanSummary,
  type BrandHostScanResult,
  type BrandHostScanStatus,
  type BrandPageScanResult,
} from "./evaluate-brand-scan.js";
export {
  evaluatePageCoverage,
  isHostPatchable,
  type CategoryCoverageSummary,
  type CoverageEvaluationResult,
  type CoverageGateTotals,
  type CoverageHostIssue,
  type CoverageHostIssueKind,
} from "./evaluate-coverage.js";
export {
  normalizeAppRoute,
  pccHostsForBrandAction,
  pccManifestMatchesRoute,
} from "./pcc-brand-bulk.js";
export {
  PROTOCOL_VERSION,
  type ClientMessage,
  type ClientPatchApply,
  type ClientPatchUndo,
  type ClientPing,
  type ClientSelect,
  type ClientTagElement,
  type Breakpoint,
  clientMessageSchema,
  clientPatchApplySchema,
  clientPatchUndoSchema,
  clientPingSchema,
  clientSelectSchema,
  clientTagElementSchema,
  duplicateIdErrorSchema,
  duplicateIdOccurrenceSchema,
  type DuplicateIdError,
  type IndexWireEntry,
  classNameModeSchema,
  type WireClassNameMode,
  libraryIdSchema,
  type LibraryId,
  indexEntrySchema,
  textTargetSchema,
  type TextWireTarget,
  styleTargetSchema,
  type StyleWireTarget,
  hierarchyRoleSchema,
  type HierarchyRole,
  type RiskLevel,
  riskLevelSchema,
  type RuntimeDiagnostics,
  runtimeDiagnosticsSchema,
  parseClientMessage,
  parseServerMessage,
  type PatchOp,
  patchOpDuplicateHostSchema,
  patchOpMergeTailwindSchema,
  patchOpMoveSiblingSchema,
  patchOpSchema,
  patchOpSetHiddenSchema,
  patchOpSetTextSchema,
  patchOpSetTableDataFieldSchema,
  rowTargetSchema,
  type RowWireTarget,
  tableMetaSchema,
  type TableMeta,
  tableDataFieldSchema,
  type TableDataFieldBinding,
  breakpointSchema,
  type ServerIndexReady,
  type ServerMessage,
  type ServerPatchAck,
  type ServerPatchUndoAck,
  type ServerSelectAck,
  type ServerTagElementAck,
  serializeServerMessage,
  serverErrorSchema,
  serverIndexReadySchema,
  serverMessageSchema,
  serverPatchAckSchema,
  serverPatchUndoAckSchema,
  serverPongSchema,
  serverSelectAckSchema,
  serverTagElementAckSchema,
} from "./protocol.js";
export {
  detectShadcnComponentMode,
  formatLibraryList,
  inferLibraryFromFilePath,
  isShadcnCompoundTag,
  LIBRARY_IDS,
  libraryGuidanceForEntry,
  librarySegmentForTag,
  resolveEntryLibraryHint,
} from "./library-registry.js";
export {
  isValidRteId,
  RTE_ID_PATTERN,
  suggestRteId,
} from "./suggest-rte-id.js";
